import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Box from '../components/Box'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>こんにちは</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-5xl font-bold underline">Hello world!</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
