import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Box from '../components/Box'
import { Button } from '../components/Box/button'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>skillforest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="bg-gradient-to-r from-red-100 via-orange-100 to-blue-100">
        <header className={styles.header}>
          <div class="bg-gray-100 w-auto h-auto">
            <div class="font-bold text-4xl">skillforest</div>
            <nav>
              <ul>
                <li>今すぐ登録</li>
                <li>お問い合わせ</li>
              </ul>
            </nav>
          </div>
        </header>

        <main className={styles.main}>
          <div>
            <h1 class="text-4xl text-blue-600 font-extrabold ">あなたのスキルを、可視化する</h1>
            <div>
              <button class="btn m-5">今すぐ登録</button>
              <button class="btn m-5">もっと読む</button>
            </div>
          </div>

          <div>
            <h1 class="text-2xl font-bold">自分のエンジニアスキルが、目に見えてわかった。</h1>
            <p>
              エンジニアであるあなたに用意した項目に答えていただくことで、あなたの市場価値を判定します。
            </p>
          </div>

          <div>
            <h1 class="text-2xl font-bold">エンジニアとしてのキャリアを考える</h1>
            <h1 class="text-2xl font-bold">skillforestが提供すること</h1>
            <ul>
              <li>あなたのエンジニアのスキルを可視化。市場価値を判定し、キャリアを支援します。</li>
              <li>エンジニアとしてのスキルアップのために身につけるべきスキルを提案します。</li>
              <li>あなたのスキルを求めている企業との自動マッチングシステムを提供。</li>
            </ul>
          </div>

          <div>
            <h1 class="text-2xl font-bold">利用フロー</h1>
            <ul class="flex justify-center bg-gray">
              <li class="text-gray-700 text-center bg-gray-400 px-4 py-2 m-2">質問に回答</li>
              <li class="text-gray-700 text-center bg-gray-400 px-4 py-2 m-2">市場価値の判定</li>
              <li class="text-gray-700 text-center bg-gray-400 px-4 py-2 m-2">企業とのマッチ</li>
            </ul>
          </div>
        </main>

        <footer className={styles.footer}>
          <div class="bg-gray-100 p-10 text-4xl font-bold">skillforest</div>
        </footer>
      </div>
    </div>
  )
}
